// Maps AI-normalized English material names to localized display names.
// Keys must match what google-ai.ts normalizes to — these are also used as
// analytics keys in analytics.ts, so never change them.
// To add a language: add a new entry to `translations` with the locale code.

const translations: Record<string, Record<string, string>> = {
  en: {
    cotton: "Cotton",
    "organic cotton": "Organic Cotton",
    "recycled cotton": "Recycled Cotton",
    polyester: "Polyester",
    "recycled polyester": "Recycled Polyester",
    nylon: "Nylon",
    "recycled nylon": "Recycled Nylon",
    polyamide: "Polyamide",
    linen: "Linen",
    wool: "Wool",
    "merino wool": "Merino Wool",
    cashmere: "Cashmere",
    alpaca: "Alpaca",
    angora: "Angora",
    mohair: "Mohair",
    silk: "Silk",
    hemp: "Hemp",
    bamboo: "Bamboo",
    viscose: "Viscose",
    rayon: "Rayon",
    modal: "Modal",
    tencel: "Tencel",
    lyocell: "Lyocell",
    acrylic: "Acrylic",
    spandex: "Spandex",
    elastane: "Elastane",
    lycra: "Lycra",
    polyurethane: "Polyurethane",
    fleece: "Fleece",
    microfiber: "Microfiber",
    leather: "Leather",
    "synthetic leather": "Synthetic Leather",
    rubber: "Rubber",
    down: "Down",
    feathers: "Feathers",
  },
  pl: {
    cotton: "Bawełna",
    "organic cotton": "Bawełna organiczna",
    "recycled cotton": "Bawełna z recyklingu",
    polyester: "Poliester",
    "recycled polyester": "Poliester z recyklingu",
    nylon: "Nylon",
    "recycled nylon": "Nylon z recyklingu",
    polyamide: "Poliamid",
    linen: "Len",
    wool: "Wełna",
    "merino wool": "Wełna merino",
    cashmere: "Kaszmir",
    alpaca: "Alpaka",
    angora: "Angora",
    mohair: "Mohair",
    silk: "Jedwab",
    hemp: "Konopie",
    bamboo: "Bambus",
    viscose: "Wiskoza",
    rayon: "Rayon",
    modal: "Modal",
    tencel: "Tencel",
    lyocell: "Lyocell",
    acrylic: "Akryl",
    spandex: "Spandeks",
    elastane: "Elastan",
    lycra: "Lycra",
    polyurethane: "Poliuretan",
    fleece: "Polar",
    microfiber: "Mikrofibra",
    leather: "Skóra",
    "synthetic leather": "Skóra syntetyczna",
    rubber: "Guma",
    down: "Puch",
    feathers: "Pierze",
  },
  de: {
    cotton: "Baumwolle",
    "organic cotton": "Bio-Baumwolle",
    "recycled cotton": "Recycelte Baumwolle",
    polyester: "Polyester",
    "recycled polyester": "Recyceltes Polyester",
    nylon: "Nylon",
    "recycled nylon": "Recyceltes Nylon",
    polyamide: "Polyamid",
    linen: "Leinen",
    wool: "Wolle",
    "merino wool": "Merinowolle",
    cashmere: "Kaschmir",
    alpaca: "Alpaka",
    angora: "Angora",
    mohair: "Mohair",
    silk: "Seide",
    hemp: "Hanf",
    bamboo: "Bambus",
    viscose: "Viskose",
    rayon: "Rayon",
    modal: "Modal",
    tencel: "Tencel",
    lyocell: "Lyocell",
    acrylic: "Acryl",
    spandex: "Spandex",
    elastane: "Elasthan",
    lycra: "Lycra",
    polyurethane: "Polyurethan",
    fleece: "Fleece",
    microfiber: "Mikrofaser",
    leather: "Leder",
    "synthetic leather": "Kunstleder",
    rubber: "Gummi",
    down: "Daune",
    feathers: "Federn",
  },
  es: {
    cotton: "Algodón",
    "organic cotton": "Algodón orgánico",
    "recycled cotton": "Algodón reciclado",
    polyester: "Poliéster",
    "recycled polyester": "Poliéster reciclado",
    nylon: "Nailon",
    "recycled nylon": "Nailon reciclado",
    polyamide: "Poliamida",
    linen: "Lino",
    wool: "Lana",
    "merino wool": "Lana merina",
    cashmere: "Cachemira",
    alpaca: "Alpaca",
    angora: "Angora",
    mohair: "Mohair",
    silk: "Seda",
    hemp: "Cáñamo",
    bamboo: "Bambú",
    viscose: "Viscosa",
    rayon: "Rayón",
    modal: "Modal",
    tencel: "Tencel",
    lyocell: "Lyocell",
    acrylic: "Acrílico",
    spandex: "Spándex",
    elastane: "Elastano",
    lycra: "Licra",
    polyurethane: "Poliuretano",
    fleece: "Forro polar",
    microfiber: "Microfibra",
    leather: "Cuero",
    "synthetic leather": "Cuero sintético",
    rubber: "Goma",
    down: "Plumón",
    feathers: "Plumas",
  },
};

export function getMaterialName(name: string, lang: string): string {
  const map = translations[lang] ?? translations.en;
  return map[name.toLowerCase()] ?? name;
}
